### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by rschev** [dgcloud/alfresco-value-assistance#11]
Please include a license so I know under what conditions I'm allowed to modify this code.

GitHub has [a site to help you find a suitable license](https://choosealicense.com/), and Alfresco tends to go with the LGPLv3.

**Comment by douglascrp** [comment]
@rschev 
Done with commit https://github.com/dgcloud/alfresco-value-assistance/commit/8415d22f37213143d65392a2e5a50ba648f01c92
