### ISSUE TITLE
2-level-demo not working

### ISSUE THREAD

**Issue by zhasik92** [dgcloud/alfresco-value-assistance#7]
![2016-11-11 17-48-36](https://cloud.githubusercontent.com/assets/11673656/20218748/82db7750-a83f-11e6-868e-9e457592dbec.png)
1) I've installed amp to Alfresco 5.1.
2) created datalist with name 2-level-demo
3) when I try to edit properties of a File with demoCascading2Level aspect I'm getting error in browser console: 404 dependent-control.js  file not found and dynamic-dropdown.js file not found.
Do you know how to fix it?

**Comment by douglascrp** [comment]
@zhasik92 Sorry for the really late response on this one, but I guess you should try again, as I have been doing lots of changes since you raised this issue.
Please, let me know if this is still a problem, or if we can close it.

Thank you, and sorry again.

**Comment by douglascrp** [comment]
As I have not received any feedback on this, I am going to close it.
