### ISSUE TITLE
Additional levels

### ISSUE THREAD

**Issue by ArnoLP** [dgcloud/alfresco-value-assistance#8]
I just tried this add-on, and it works fine, as far as I tested it (with Alfresco 5.0.d community).
Thanks for it.

I would need to add 1 or 2 levels to it.

Could you give me some information which would help me to understand how it should be handled, where to look at (components, scripts, config files, ...), ... so that I can try to add these levels ?

Thanks in advance for the help you can provide.

**Comment by douglascrp** [comment]
Is this still a problem?
Can I close it?

**Comment by ArnoLP** [comment]
Yes, it can be closed.

**Comment by douglascrp** [comment]
Ok. Thank you.

Closing it
