### ISSUE TITLE
extend more than 2 levels

### ISSUE THREAD

**Issue by Dnhatsave** [dgcloud/alfresco-value-assistance#9]
Hi all,
first of all I've implement the addon recently and its works perfectly. :+1: 
Recently had the need to extend the dependency levels to 3 or 4, I have tried to implement without success ... with the following approach:

1. on **demoModel.xm**l : I've create a new aspect eg: 

```
<aspect name="dm:demoCascading3Level">
<title>Demo Cascading Aspect</title>
<properties>
<property name="dm:level1">
...
</property>
<property name="dm:level2">
...
</property>
<property name="dm:level3">
...
</property>
</properties>
</aspect>`
```

2. I've do the same thing on **valueAssistenceModel.xml** :

```
<type name="va:3LevelCascadingValueAssistanceListItem">
<title>3 Level Cascading Value Assistance List</title>
<parent>dl:dataListItem</parent>
<archive>false</archive>
<mandatory-aspects>
<aspect>va:level1Aspect</aspect>
<aspect>va:level2Aspect</aspect>
<aspect>va:level3Aspect</aspect>
</mandatory-aspects>
</type>
<aspects>
<aspect name="va:level1Aspect">
<title>Level 1 Aspect</title>
....
</aspect>
<aspect name="va:level2Aspect">
<title>Level 2 Aspect</title>
....
</properties>
</aspect>
<aspect name="va:level3Aspect">
<title>Level 3 Aspect</title>
...
</aspect>
</aspects>
```

3. and finaly I've do this on###  **share-config-costum.xml** : 

```
<config evaluator="aspect" condition="dm:demoCascading3Level">
<forms>
<form>
<field-visibility>
<show id="dm:level1" />
<show id="dm:level2" />
<show id="dm:level3" />
</field-visibility>
<appearance>
<field id="dm:level1">
<control template="/form-controls/dynamic-dropdown.ftl">
<control-param name="picklistName">2-level-demo</control-param>
<control-param name="level">1</control-param>
<control-param name="loadLabel">true</control-param>
</control>
</field>
<field id="dm:level2">
<control template="/form-controls/dynamic-dropdown.ftl">
<control-param name="picklistName">2-level-demo</control-param>
<control-param name="level">2</control-param>
<control-param name="dependsOn">prop_dm_level1</control-param>
<control-param name="loadLabel">true</control-param>
</control>
</field>
<field id="dm:level3">
<control template="/form-controls/dynamic-dropdown.ftl">
<control-param name="picklistName">2-level-demo</control-param>
<control-param name="level">3</control-param>
<control-param name="dependsOn">prop_dm_level2</control-param>
<control-param name="loadLabel">true</control-param>
</control>
</field>
</appearance>
</form>
</forms>
</config>
```

the result I got, is that I was able to populate all fields of the data list and the dependency still work for the 2 levels. The Problem is no data is returned at the 3 level of dependency. 

I know that this functionality is outside the scope of this project, but I would appreciate it if you could help me implement this requirement. 

Best regards
Dercio.

**Comment by douglascrp** [comment]
Hello.
Thanks for the interest and the feedback.
Unfortunately, there is no easy way to implement this feature, and I have not tried to implement it by myself.
Because of that, I have not tip to share with you.

What you "could" do it to use the third level as a common second level dependency on the second field.
Inside your datalist configuration, you could play with the value field, that is the one used as the key.
Something like:

First datalist:
```
value 1 | label 1 | value 2 | label 2
-------------------------------------
A       | A1      | A1-A    | A1A
-------------------------------------
```

Second datalist:
```
value 1 | label 1 | value 2 | label 2
-------------------------------------
A1-A    | A1A     | B1-A    | B1A
-------------------------------------
```

As the value for the first level on the second datalist is the same as the second level in the first datalist, that would simulate the desired requirement.

Try it and let me know if you need help on this.

**Comment by Dnhatsave** [comment]
Thanks for reply me Douglas,
I know that is no easy way to implement this feature but lets try.

I'm confused, you say

> As the value for the first level on the second datalist is the same as the second level in the first datalist, that would simulate the desired requirement.

"I think" that following this approach would simulate a 3-level dependency only if the second value in the first data list equals the first in the second data list.

in my case, i've something like that:
```

  | Level 1 Value    | Level 1 Label     |Level 2 Value   |Level 2 Label   | Level 3 Value   |Level 3 Label 
---------------------------------------------------------------------------------------------------------------------
  | classe 1         | classe 1          | sub classe 1  | sub classe 1   | grupo 1          | grupo 1 |  
  | classe 1         | classe 1          | sub classe 2  | sub classe 2   | grupo 2          | grupo 2 |  
  | classe 1         | classe 1          | sub classe 2  | sub classe 2   | grupo 3          | grupo 3 |  
  | classe 2         | classe 2          | sub classe 1  | sub classe 1   | grupo 1          | grupo 1
``` 

so... how could i use your approach in that situation?

**Comment by douglascrp** [comment]
It would be something like this:

List 1

```
  | Level 1 Value    | Level 1 Label     |Level 2 Value   |Level 2 Label
------------------------------------------------------------------------
  | classe 1         | classe 1          | sub classe 1  | sub classe 1 
  | classe 1         | classe 1          | sub classe 2  | sub classe 2 
  | classe 1         | classe 1          | sub classe 2  | sub classe 2 
  | classe 2         | classe 2          | sub classe 1  | sub classe 1 
```


List 2
```
  | Level 1 Value    | Level 1 Label     |Level 2 Value   |Level 2 Label
------------------------------------------------------------------------
  | sub classe 1     | sub classe 1      | grupo 1        | grupo 1
  | sub classe 2     | sub classe 2      | grupo 2        | grupo 2
  | sub classe 2     | sub classe 1      | grupo 3        | grupo 3
  | sub classe 1     | sub classe 1      | grupo 1        | grupo 1
```

**Comment by Dnhatsave** [comment]
well I've only one list as you can see, and i populate all 3 fields on this list.

If i create another second list i'll not able to use it, because only the the first list will be displayed  on my dropdowns.

**Comment by Dnhatsave** [comment]
to create a List 2

> List 2
> 
>   | Level 1 Value    | Level 1 Label     |Level 2 Value   |Level 2 Label
> ------------------------------------------------------------------------
>   | sub classe 1     | sub classe 1      | grupo 1        | grupo 1
>   | sub classe 2     | sub classe 2      | grupo 2        | grupo 2
>   | sub classe 2     | sub classe 1      | grupo 3        | grupo 3
>   | sub classe 1     | sub classe 1      | grupo 1        | grupo 1
> 

 its necessary to configure another aspect at Model?

**Comment by douglascrp** [comment]
@Dnhatsave sorry for the laaaaate response.
Were you able to solve your issue?
Is this still a problem for you, or should I close it?

**Comment by douglascrp** [comment]
As I got no answer, I am closing this.
Feel free to reopen it if the problem persists.
